
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Dbsys.AppData
{

using System;
    using System.Collections.Generic;
    
public partial class View_2
{

    public string accountNumber { get; set; }

    public string fullName { get; set; }

    public string phoneNumber { get; set; }

    public string Email { get; set; }

    public string userStatus { get; set; }

    public string createdBy { get; set; }

    public int userId { get; set; }

}

}
